/*
View para consultas de categorias  e subcategorias
*/
DROP VIEW IF EXISTS LISTA_CAT_E_SUBCAT;
CREATE VIEW LISTA_CAT_E_SUBCAT AS SELECT TIPO_CAT AS TIPO, DESCR_CAT AS CATEGORIAS, DESCR_SUBCAT AS SUBCATEGORIAS
	FROM CATEGORIA C
    LEFT JOIN SUBCATEGORIAS S ON C.COD_CAT = S.COD_CAT
    ORDER BY TIPO ASC,
			 CATEGORIAS ASC,
			 SUBCATEGORIAS ASC;
    
-- VISUALIZAÇÃO:
SELECT * FROM LISTA_CAT_E_SUBCAT;